spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: user_test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/news_db
    user: user_test
    password: test
    drop-first: false